### ISSUE TITLE
Output depends on libclang version.

### ISSUE THREAD

**Issue by mahkoh** [crabtw/rust-bindgen#101]
Some people report that clang 3.3 turns
```c
int i[][1];
```
into
```rust
extern "C" {
    pub static mut i: *mut ::libc::c_void;
}
```
but 3.4 produces ~~the correct~~ (edit: this is also incorrect. see the other issue regarding arrays)
```rust
extern "C" {
    pub static mut i: *mut [::libc::c_int, ..1u];
}
```

**Comment by Yamakaky** [comment]
What should be the correct output?

**Comment by Yamakaky** [comment]
Fixed by https://github.com/crabtw/rust-bindgen/pull/327
