### ISSUE TITLE
Generate proper enums

### ISSUE THREAD

**Issue by fread2281** [crabtw/rust-bindgen#109]
It would be really nice if rust-bindgen would generate proper enums (for enums in C) instead of a type alias and constants.

**Comment by aldanor** [comment]
Wouldn't this
```rust
pub type Enum_Unnamed1 = c_int;
pub const A: c_int = -1;
pub const B: c_int = 0;
pub type TestEnum_t = Enum_Unnamed1;
```
be better as this? (are there any pitfalls?)
```rust
pub type TestEnum_t = c_int;
pub const A: TestEnum_t = -1;
pub const B: TestEnum_t = 0;
```

**Comment by davekong** [comment]
What if this
```c
/**
 *  \brief The blend mode used in SDL_RenderCopy() and drawing operations.
 */
typedef enum
{
    SDL_BLENDMODE_NONE = 0x00000000,     /**< no blending
                                              dstRGBA = srcRGBA */
    SDL_BLENDMODE_BLEND = 0x00000001,    /**< alpha blending
                                              dstRGB = (srcRGB * srcA) + (dstRGB * (1-srcA))
                                              dstA = srcA + (dstA * (1-srcA)) */
    SDL_BLENDMODE_ADD = 0x00000002,      /**< additive blending
                                              dstRGB = (srcRGB * srcA) + dstRGB
                                              dstA = dstA */
    SDL_BLENDMODE_MOD = 0x00000004       /**< color modulate
                                              dstRGB = srcRGB * dstRGB
                                              dstA = dstA */
} SDL_BlendMode;
```

could be turned into something like this

```
#[repr(C)]
enum SDL_BlendMode {
    NONE = 0x00_00_00_00,
    BLEND = 0x00_00_00_01,
    ADD = 0x00_00_00_02,
    MOD = 0x00_00_00_04,
}

impl CEnum for SDL_BlendMode {
    fn to_c_int(&self) -> c_int {
        *self as c_int
    }

    fn from_c_int(v: c_int) -> SDL_BlendMode {
        unsafe { mem::transmute(v) }
    }
}
```
Then the C functions can be wrapped using these to and from methods.

**Comment by bjz** [comment]
I would prefer constants because they are closer to the semantics of C enums. Plus you can do bitwise operations on them if needed. Proper enums are more in the domain of Rust wrappers that ffi bindings.

**Comment by aldanor** [comment]
It would be nice to be able to have it either way (via command-line switch?):

Version 1, via consts -- this is just a disconnected set of top-level type definitions and consts though so if you have many of them it could get quite messy (there's also no way to check if a specific integer is a valid value for an enum type since there's no relation between the two):
```rust
pub type Foo = c_uint;
pub const A: c_uint = 0;
pub const B: c_uint = 1;
```

Version 2 (see e.g. https://github.com/alexcrichton/git2-rs) -- this quite nice to use since it will works properly with `match` statements and is more Rust-idiomatic (you can always do a `foo as c_uint` to cast it to an integer if you really need to):
```rust
use self::Foo::*;

#[repr(C)]
#[derive(Copy)]
enum Foo {
    A = 1,
    B = 2
}
```

**Comment by bjz** [comment]
It would be:

~~~rust
pub type Foo = c_uint;
pub const A: Foo = 0;
pub const B: Foo = 1;
~~~

**Comment by pornel** [comment]
:+1: @aldanor's Version 2 is what I strongly prefer: C `enum` as Rust `enum` with `#[repr(C)]`.

**Comment by mahkoh** [comment]
Rust enums are not good at wrapping C enums for at least the following reasons:

- Rust enums with repr(C) must contain at least two variants
- Rust enums can't contain values larger than usize::MAX

**Comment by aldanor** [comment]
@mahkoh Rust enums can *sometimes* be not good at wrapping C enums, hence this behaviour could be optional, e.g. via a command line switch. Most of the time the chances are you your enum values are less than max usize and contain at least two variants. (Plus, enums with one variant can be always translated as a simple const).

**Comment by mahkoh** [comment]
As long as the default doesn't change I don't care.

**Comment by pornel** [comment]
@mahkoh Could you generate enum only in good cases? (even assuming 32-bit usize)

**Comment by nox** [comment]
This is implemented.
