### ISSUE TITLE
Recognize size_t

### ISSUE THREAD

**Issue by pornel** [crabtw/rust-bindgen#111]
When converting [jpeglib.h](https://github.com/mozilla/mozjpeg/blob/master/jpeglib.h) I'm getting:

> jpeglib.h:826:3: error: unknown type name 'size_t'

libjpeg assumes `<stdio.h>` is included first. It'd be nice if bindgen could either recognize `size_t` (and `FILE`) out of the box or understood `#include <stdio.h>`.

**Comment by Will-W** [comment]
I'm having the size_t problem, but also one with time_t. I'm generating from a header file that explicitly does the following before doing anything else:
```C
#include <time.h>
#include <stddef.h>
#include <stdint.h>
```

Surely time_t is a 'normal' typedef'd value and some a magic special built-in like size_t? What's different here? Or rather - any suggestion as to what to do to look into it more?

rust-bindgen manages to pick up all the other typedefs and their usages and generate the mappings.

**Comment by pornel** [comment]
Special support for `uint8_t`, `uint16_t`, `uint32_t` etc. would be great too (since these map perfectly to Rust).

**Comment by jnicholls** [comment]
I too have to prepend `::libc::` to size_t after generation.  This seems like something easy to fix.  I'll poke around the code and see if this can be easily taken care of.

**Comment by drbo** [comment]
`size_t` maps perfectly to Rust's `usize`

**Comment by Yamakaky** [comment]
See https://github.com/crabtw/rust-bindgen/pull/256
