### ISSUE TITLE
Silence warnings non_snake_case, non_camel_case_types

### ISSUE THREAD

**Issue by pornel** [crabtw/rust-bindgen#112]
A converted [jpeglib.h](https://github.com/mozilla/mozjpeg/blob/master/jpeglib.h) contains a lot of un-rust-like type names, which cause a flood of warnings from rustc.

It'd be great if bindgen detected presence of "bad" names and automatically silenced relevant warnings:

```rust
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
```

**Comment by nox** [comment]
I'll add these unconditionally in the output of rust-bindgen.
