### ISSUE TITLE
rust-bindgen doesn't compile on master rust

### ISSUE THREAD

**Issue by suhr** [crabtw/rust-bindgen#124]
Since `Copy` trait implementation is no longer implicit, rust-bindgen doesn't compile. Adding `#[deriving(Copy, Clone)]` to data types fixes this.

**Comment by gsingh93** [comment]
The current version works fine for me, this issue should probably be closed.

**Comment by fbernier** [comment]
It's not building right now on today's nightly. I suppose it's because they are merging breaking changes before 1.0 alpha release.

**Comment by davekong** [comment]
I just build it without any issue. The only warnings I get are about using unstable features; although, it core dumps when I try to run.
