### ISSUE TITLE
Using bindgen in Cargo build step

### ISSUE THREAD

**Issue by danburkert** [crabtw/rust-bindgen#161]
I would like to be able to use bindgen from a `build.rs` to generate bindings at compile time.  I have this set up for a library [here](https://github.com/danburkert/lmdb-rs/blob/master/lmdb-sys/build.rs), but I can't find a way to get it to work on Linux (it works on OS X if the `DYLD_LIBRARY_PATH` is set to include clang).  I believe this is related to #89, but I'm not sure how to work around it in this case.  Thanks for any help!

**Comment by nox** [comment]
Can you retry on last master?

**Comment by danburkert** [comment]
I ended up heavily modifying the output from bind gen and the checking it in, so this is no longer an issue for me.  Thanks for the help, though.
