### ISSUE TITLE
Ability to specify calling convention

### ISSUE THREAD

**Issue by jminer** [crabtw/rust-bindgen#162]
As explained on the [FFI page](http://doc.rust-lang.org/book/ffi.html#foreign-calling-conventions), Windows functions use `stdcall` on 32-bit and `C` on 64-bit. Rust provides "system" that matches that. The exception is that on 32-bit, Windows uses the `C` calling convention for variadic functions. Third-party libraries don't necessarily do the same. I just checked that cairo and PortAudio use `C` on 32-bit Windows.

When I run the Windows header files through bindgen, all of them come out `extern "C"`. They need to all be `extern "system"` except for variadic functions that need to be `extern "C"`. I thought of a couple possibilities that would make it easier:

- If Clang exposes the calling convention in the AST, maybe bindgen could use that.
- Alternatively, maybe there could be a command line argument to specify the calling convention, with the argument being ignored for variadic functions.

**Comment by nox** [comment]
Pretty sure we handle calling conventions now, but it needs tests.

**Comment by Yamakaky** [comment]
http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga4a0e941ec7b4b64bf9eb3d0ed49d55ae
https://github.com/crabtw/rust-bindgen/blob/master/src/parser.rs#L146

**Comment by Yamakaky** [comment]
stdcall seems supported

**Comment by Yamakaky** [comment]
Closing until finds a real problem.
