### ISSUE TITLE
Preserve hex constants

### ISSUE THREAD

**Issue by pornel** [crabtw/rust-bindgen#165]
[Mozjpeg has enums of GUIDs](
https://github.com/mozilla/mozjpeg/blob/0aea1da9f0c8577e7fde4ff99c5e75dfdf075472/jpeglib.h#L276
):

```c
typedef enum {
  JBOOLEAN_OPTIMIZE_SCANS = 0x680C061E, /* TRUE=optimize progressive coding scans */
```

bindgen changes these constants to decimal, and sometimes even interprets them as negative numbers! 
I think it's safe to assume that notation is important and use the same notation in Rust.

**Comment by nox** [comment]
The negative number part should be fixed by #263.

**Comment by nox** [comment]
For the hex formatting, there is nothing we can do, Clang just gives the integer value, AFAIK.

**Comment by pornel** [comment]
Would you accept a solution based on a heuristic? (e.g. pick representation that has more 0s or repeated digits)

**Comment by nox** [comment]
Why does it matter?

**Comment by pornel** [comment]
Esthetics, and hopefully closer to representing original code.

When I build wrappers for libraries I use bindgen to generate a "first draft" of Rust files, which then I clean up and maintain manually, so I'd like them to be nice and readable.

**Comment by nox** [comment]
To each their own I guess. :) Our intent with the use of rust-bindgen in Servo is to never have to maintain them manually.

Can you confirm that the underflow is fixed with my PR, btw?

**Comment by pornel** [comment]
I can confirm that enums are positive decimal integers now.

**Comment by nox** [comment]
@pornel Cool! Thanks for the feedback.
