### ISSUE TITLE
Use typedef name instead of unnamed struct name

### ISSUE THREAD

**Issue by pornel** [crabtw/rust-bindgen#169]
Unnamed struct + typedef:

```c
typedef struct {
…
} foo;
```

is currently translated quite literally to:

```rust
pub struct Struct_Unnamed1 {
…
}
pub type foo = Struct_Unnamed1;
```

I think it would be more elegant to use name from the typedef as struct name and translate it as:

```rust
struct foo {
…
}
```

**Comment by tupshin** [comment]
+1 
Also true for enums. 
    typedef enum { ... } cass_bool_t;

Comes out as

    pub enum Enum_Unnamed1 {
    ...
    }
    pub type cass_bool_t = Enum_Unnamed1;

And similarly could, and should, just be: 
    pub enum cass_bool_t {
    ...
    }

**Comment by Yamakaky** [comment]
It seems that the clang parser separate `struct` and `typedef`, so I think the only possibility is to check in the ast for typedefs following struct definitions. I don't know how it would play with imbricated structs, though. See TranslationUnit::parse.

**Comment by crumblingstatue** [comment]
This causes problems for typedefed enums, due to https://github.com/rust-lang/rust/issues/26264.

Not to mention it pollutes the namespace, causing name conflicts if you glob import from multiple crates.

I'm currently trying to convert [rust-sfml](https://github.com/jeremyletang/rust-sfml) to bindgen, but I'm running into the above problems.

**Comment by Yamakaky** [comment]
So we should definitively do it ^^
For the glob import, you mean for example when there are multiples Struct_UnnamedX?

**Comment by crumblingstatue** [comment]
> For the glob import, you mean for example when there are multiples Struct_UnnamedX?

Yes, that's what I mean.

**Comment by Yamakaky** [comment]
What do you think?

**Comment by crumblingstatue** [comment]
> What do you think?

Thanks for the quick implementation! I'll test it on rust-sfml and report back on the PR.

**Comment by Yamakaky** [comment]
Cool

**Comment by pornel** [comment]
Thank you :)
