### ISSUE TITLE
error while loading shared libraries: libbindgen-6308835211e9d4a3.so

### ISSUE THREAD

**Issue by NobbZ** [crabtw/rust-bindgen#172]
When trying to run bindgen after applying #171 I get the following message:

```plain
$ ./target/bindgen
./target/bindgen: error while loading shared libraries: libbindgen-6308835211e9d4a3.so: cannot open shared object file: No such file or directory

$ ls target
bindgen  build  deps  examples  libbindgen-6308835211e9d4a3.so  native
```

So bindgen fails finding a while, which is actually there…

**Comment by cmr** [comment]
@NobbZ this is because the binary is dynamically linking without setting an rpath or putting the library in the runtime linker's search path. Set LD_LIBRARY_PATH to target, or edit the Cargo.toml to [set the rpath](http://doc.crates.io/manifest.html#the-[profile.*]-sections)

**Comment by NobbZ** [comment]
OK, now I get a segfault… The dumped core is about 25MiB and doesn't tell me anything…

**Comment by cmr** [comment]
@NobbZ well known issue as linked from the README: https://github.com/crabtw/rust-bindgen/issues/88

**Comment by NobbZ** [comment]
Oh... I read it, but did not consider that as the actual problem, since that bug is open for half of a year now and there happened a release in the meanwhile. I thought it just got forgotten to get closed… But yes, using `LD_PRELOAD` did it.

**Comment by bjz** [comment]
It would be nice if there was a more robust way of handling this....

**Comment by mahkoh** [comment]
The robust way is to remove the useless plugin stuff:
```patch
diff --git a/Cargo.toml b/Cargo.toml
index 435bac8..c6156e0 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -11,10 +11,8 @@ build = "build.rs"
 static = []
 
 [lib]
-
 name = "bindgen"
 path = "src/lib.rs"
-plugin = true
 
 [[bin]]
 
diff --git a/src/lib.rs b/src/lib.rs
index 27a5245..5be4045 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1,9 +1,8 @@
 #![crate_name = "bindgen"]
-#![crate_type = "dylib"]
-#![feature(quote, plugin_registrar, unboxed_closures, rustc_private, libc)]
+#![crate_type = "lib"]
+#![feature(quote, unboxed_closures, rustc_private, libc)]
 
 extern crate syntax;
-extern crate rustc;
 extern crate libc;
 #[macro_use] extern crate log;
 
@@ -16,7 +15,6 @@ use syntax::codemap::{DUMMY_SP, Span};
 use syntax::print::{pp, pprust};
 use syntax::print::pp::eof;
 use syntax::ptr::P;
-use rustc::plugin::Registry;
 
 use types::Global;
 
@@ -28,12 +26,6 @@ mod gen;
 mod parser;
 mod bgmacro;
 
-#[doc(hidden)]
-#[plugin_registrar]
-pub fn plugin_registrar(reg: &mut Registry) {
-    reg.register_macro("bindgen", bgmacro::bindgen_macro);
-}
-
 pub struct BindgenOptions {
     pub match_pat: Vec<String>,
     pub builtins: bool,
```
No more LD_PRELOAD nonsense necessary.

**Comment by Yamakaky** [comment]
Could you make a PR if the problem is still there?
