### ISSUE TITLE
Not linking against LLVMAnalysis

### ISSUE THREAD

**Issue by TyOverby** [crabtw/rust-bindgen#179]
```
error: could not find native static library `LLVMAnalysis`, perhaps an -L flag is missing?
Could not compile `rust-bindgen`.
```

**Comment by mitchmindtree** [comment]
I'm also getting this. I've also successfully compiled this a couple weeks ago, so the issue must have only been recently introduced.

**Comment by TyOverby** [comment]
@mitchmindtree and I think that it started in this https://github.com/crabtw/rust-bindgen/pull/177

**Comment by mitchmindtree** [comment]
Can confirm, [this](https://github.com/mitchmindtree/rust-bindgen/commit/b764fe6a0867daae83155d0e8c74eb3d435deca0) fixes it for me.

**Comment by crabtw** [comment]
Now bindgen uses dynamic linking by default.
That should fix the problem. Please try latest commit.

**Comment by mitchmindtree** [comment]
@crabtw I just tested the latest commit and it builds fine, thanks :+1:

**Comment by nox** [comment]
See #277.
