### ISSUE TITLE
crash detected during parsing

### ISSUE THREAD

**Issue by andbass** [crabtw/rust-bindgen#189]
Whenever I attempt to generate bindings for a header file, I get the following error message:
```
unexpected OS for Darwin triple
UNREACHABLE executed at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/Support/Triple.cpp:737!
libclang: crash detected during parsing: {
  'source_filename' : ''
  'command_line_args' : ['test.h'],
  'unsaved_files' : [],
  'options' : 0,
}
```

I'm running 64 bit Linux with Clang 3.5.

**Comment by andrewjstone** [comment]
I'm seeing the same issue on freebsd with clang-devel-3.7

**Comment by cocreature** [comment]
I can reproduce this with clang 3.6.0 (on archlinux). LD_PRELOADing libclang.so doesn't change anything.
