### ISSUE TITLE
error: macro undefined: 'bindgen!' with github rust

### ISSUE THREAD

**Issue by MichaelRiss** [crabtw/rust-bindgen#201]
I'm using rust from github (https://github.com/rust-lang/rust/commit/d3724342a3ef8eff3473de988f80bc088dc2668d) and when running "cargo test" in rust-bindgen (https://github.com/crabtw/rust-bindgen/commit/9628cb08d1d454d2d331db46a10fbd356f444663) I get the following error:
```
tests/test_cmath.rs:2:15: 2:22 error: macro undefined: 'bindgen!'
tests/test_cmath.rs:2 pub mod ffi { bindgen!("/usr/include/math.h", link = "m"); }
                                    ^~~~~~~
error: aborting due to previous error
Could not compile `rust-bindgen`.
```
Shouldn't this work? Or did I make a mistake somewhere?

**Comment by tupshin** [comment]
A working example of this would be greatly appreciated. I don't see any existing project that has working use of bindgen as a macro. Would be a killer feature.

**Comment by bfops** [comment]
I'm entirely unable to get this macro working, too. I have to tweak the example code (specifically the `phase` part) to even get as far as the "macro undefined" error.

**Comment by bfops** [comment]
I think I got it to work by switching to the new `#![plugin(rust_bindgen)]` syntax, e.g.

    #![feature(plugin)]
    #![plugin(bindgen_plugin)]

    #[allow(dead_code, uppercase_variables, non_camel_case_types)]
    mod mysql_bindings {
      bindgen!("/usr/include/mysql/mysql.h", match="mysql.h", link="mysql");
    }

I'm getting llvm assertion failures, but I think they're unrelated to this issue.

**Comment by kkimdev** [comment]
@bfops I'm getting this error.. what am I missing?

src/lib.rs:13:11: 13:25 error: can't find crate for `bindgen_plugin`
src/lib.rs:13 #![plugin(bindgen_plugin)]

**Comment by bfops** [comment]
@kkimdev `Cargo.toml` needs to point to `bindgen_plugin` instead of `bindgen`. I'm not sure if this is doable directly from the github repo. I ended up giving up on the macro and using `bindgen` from my `build.rs`, which isn't documented in the README.

**Comment by kkimdev** [comment]
@bfops So do you directly execute the command line in `build.rs`? Could you share your `build.rs`? Thanks!

**Comment by bfops** [comment]
@kkimdev Oops, I should have clarified I meant the `bindgen` **library**. My `build.rs` is linked in my previous post.

**Comment by kkimdev** [comment]
@bfops oh thanks, missed your link. Actually I slightly perfer `build.rs` approach more, since it's more explicit that we're generating an intermediate `.rs` binding, and can be inspected easily.

**Comment by jramapuram** [comment]
Anyone know how to pass in a clang arg to the builder? I.e something like `-I myIncFolder ` ?

**Comment by bfops** [comment]
@jramapuram It's a little silly, but it looks like you could use [`header`](https://github.com/crabtw/rust-bindgen/blob/e9b2f7a2d401edf6b7662b187bd415253b072df5/src/lib.rs#L40) to do it.

**Comment by jramapuram** [comment]
@bfops : I tried that! I.e. directly calling `bindings.header("-I myIncFolder[Fully qualified]")` however it didn't seem to work =/. 

I still see: `fatal error: myIncFolder/myheader.h` file not found

**Comment by bfops** [comment]
@jramapuram I think `-I` adds a directory to search for headers, not a specific header file. If that's not the problem, maybe try passing the `-I` and the folder as two separate strings, although I don't think it should matter..

**Comment by jramapuram** [comment]
To clarify: I did want an entire folder added. Mainly because within the project things are referenced as `#include "myIncFolder/header1.h"` etc. In a makefile this would just be blobbed into the VPATH.

But your suggestion worked! Thanks a bunch! I did:
```rust
bindings.header("-I");
bindings.header("myIncFolder");
```

**Comment by bfops** [comment]
Oh whoops my brain glitched when I read your last post. Glad the change worked! I feel like the `header` function should be renamed..

**Comment by jramapuram** [comment]
Most definitely, it should just be clang_args or something similar. Thanks again!

**Comment by bfops** [comment]
I'll submit a PR

**Comment by jimrandomh** [comment]
Came across this thread hoping to find a working example of using the bindgen macro. Using what's in the readme, I get a macro undefined error. Starting from what's in the readme and changing the dependency on bindgen to instead be a dependency on bindgen_plugin, I get:

    /home/jbabcock/.cargo/registry/src/github.com-88ac128001ac3a9a/bindgen_plugin-0.16.0/src/lib.rs:3:1: 3:45 error: #[feature] may not be used on the stable release channel

(With rustc 1.6.0 (c30b771ad 2016-01-19).)

**Comment by Yamakaky** [comment]
bindgen_plugin is only usable on nightly for now.
