### ISSUE TITLE
Needs a testsuite

### ISSUE THREAD

**Issue by luser** [crabtw/rust-bindgen#225]
I wound up hacking on rust-bindgen a bit and making a few somewhat invasive changes, but there's no testsuite. :-(

I think a simple set of C headers + expected Rust output would be useful for regression testing, at least.

**Comment by ebarnard** [comment]
There is a test suite, although admittedly not comprehensive. Run `cargo test` or see https://github.com/crabtw/rust-bindgen/tree/master/tests.

**Comment by ebarnard** [comment]
It should really be documented somewhere.
