### ISSUE TITLE
Use types from `std::os::raw` in place of `libc`

### ISSUE THREAD

**Issue by mbrubeck** [crabtw/rust-bindgen#240]
The [`std::os::raw`][1] module contains type aliases for c_void, c_char, c_int, etc.  Should rust-bindgen use these aliases instead of the ones in the `libc` crate, when possible?  The advantages are that `std::os::raw` is a guaranteed-stable API and does not introduce an external dependency.

cc @alexcrichton

[1]: http://doc.rust-lang.org/std/os/raw/

**Comment by alexcrichton** [comment]
This shouldn't really be a question that needs to be asked in my opinion, the two should never differ and it's a bug if they do.
