### ISSUE TITLE
rust-bindgen shouldn't use c_* types for the actual bindings

### ISSUE THREAD

**Issue by nox** [crabtw/rust-bindgen#246]
Any user should instead generate one FFI module per platform they plan to support. E.g. rust-mozjs generates jsapi_macos_64, jsapi_linux_32, jsapi_linux_64…

**Comment by michaelwu** [comment]
I don't think this is a valid for C bindings. It's a lot easier to generate cross platform bindings for C. We have to generate per platform for spidermonkey because of mangling, but even then I'd like to be able to generate the mangled names without running on every platform.

**Comment by nox** [comment]
I see. Thanks for replying. I'll close this.

**Comment by nox** [comment]
Actually, how would that help, given that compilation flags and whatnot can change various things in incompatible ways (like -fshort-enums)?

**Comment by michaelwu** [comment]
Don't do that then? The gcc man page points out that it gives you a non-default ABI.

**Comment by nox** [comment]
My point is that some flags may be needed in some projects, on some platforms, and thus you just can't avoid generating a module per platform. You say we generate one per platform just because of mangling, but what about preprocessor directives that selectively compile different functions on different systems and whatnot?

**Comment by michaelwu** [comment]
Sure, but that's your choice. You can also choose to be careful and make things work on all platforms. At this point, it's not a module per platform, but module per every possible configuration. Not everyone needs to care about that.
