### ISSUE TITLE
error: unsupported representation for univariant enum

### ISSUE THREAD

**Issue by japaric** [crabtw/rust-bindgen#255]
Given a header file contains a single variant enum:

``` C
// snip from /usr/include/cuda.h
typedef enum CUipcMem_flags_enum {
    CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 0x1 /**< Automatically enable peer access between remote devices as needed */
} CUipcMem_flags;
```

bindgen produces a non-compilable module:

``` rust
/* automatically generated by rust-bindgen */

#[derive(Clone, Copy)]
#[repr(u32)]
pub enum Enum_CUipcMem_flags_enum { CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 1, }
pub type CUipcMem_flags = Enum_CUipcMem_flags_enum;
```

That errors with:

``` rust
test.rs:5:1: 5:78 error: unsupported representation for univariant enum [E0083]
test.rs:5 pub enum Enum_CUipcMem_flags_enum { CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 1, }
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.rs:5:1: 5:78 help: run `rustc --explain E0083` to see a detailed explanation
error: aborting due to previous error
```

---

A possible solution to make bindgen generate a valid module in this case, is to follow the recommendation of `rustc --explain E0083`:

```
At present, it's not possible to define a custom representation for an enum with
a single variant. As a workaround you can add a `Dummy` variant.

See: https://github.com/rust-lang/rust/issues/10292
```

And have bindgen add a `__DUMMY` variant to the translated single-variant enum.

Does that sound like a reasonable solution?

cc @nox

**Comment by japaric** [comment]
Update: This may be fixed upstream. See rust-lang/rust#31232

**Comment by cgramza** [comment]
This is fixed upstream but stable Rust is still a problem.  We won't see rust-lang/rust#31232 until Rust 1.8, so 12 weeks from now.  There should be a workaround in place, e.g. adding a Dummy variant.  Thanks.

**Comment by japaric** [comment]
See #257 for an implementation of the solution proposed here.

**Comment by jnicholls** [comment]
Awesome @japaric thanks for the PR!

**Comment by michaelwu** [comment]
I think we need a switch to use old style enums - this isn't the only thing that can break with the fancy enum support. I'll see if I can cobble something together this week.

**Comment by Yamakaky** [comment]
For now, let's add a dummy variant. We will remove it when it's supported by rust.

**Comment by nox** [comment]
We should rather implement a flag that lets it disable Rust enums for C enums.

**Comment by nox** [comment]
See #276.
