### ISSUE TITLE
Build error message "Unable to find libclang.so" is partly wrong

### ISSUE THREAD

**Issue by julienw** [crabtw/rust-bindgen#258]
Without libclang-dev installed I got the error `Unable to find libclang.so` when I tried to build. That's kind of misleading because libclang.so was actually there and I spent time trying to give the right PATH which I couldn't.

Is it libclang.a that you really want ?

**Comment by michaelwu** [comment]
AFAIK, static linking is not used unless you explicitly ask for it. Note that depending on your distro, libclang.so may not actually exist without libclang-dev installed. Instead, you get libclang.so.X and libclang.so.X.Y.Z.

**Comment by julienw** [comment]
ah yeah, I think you're actually right here.

Maybe the error string could be improved by "Maybe you should install the libclang-dev package ?".

**Comment by nox** [comment]
@julienw Would you be willing to instead improve the build instructions in the README?

**Comment by Yamakaky** [comment]
Also, keep in mind that not everyone uses a debian-like distro ;) It's `clang` on archlinux for example.

**Comment by Yamakaky** [comment]
If you still have the problem, please report it to https://github.com/KyleMayes/clang-sys/
