### ISSUE TITLE
Derive Debug for items

### ISSUE THREAD

**Issue by WiSaGaN** [crabtw/rust-bindgen#261]
It would be useful if the generated file includes struct derived "Debug" for items
`#[derive(Debug)]`
I do not see much downside in it, and we can make this optional if there is.

**Comment by WiSaGaN** [comment]
Looks like we could get a lot of underlying not defining Debug, such as array longer than 32.
Closing this until we have better language support for array.

**Comment by nox** [comment]
Could you leave the issue open?

**Comment by WiSaGaN** [comment]
Any way to actually implement it before we have all array implementing Debug?

**Comment by nox** [comment]
@WiSaGaN Whether we can, it is still an issue. An issue blocked on some external things, but an issue nonetheless. Also, we can still derive Debug for anything that doesn't use large arrays.

**Comment by WiSaGaN** [comment]
Sure. If it can be conditionally implemented based on the underlyings.

**Comment by nox** [comment]
@WiSaGaN: @Yamakaky started working on this in #267.

**Comment by WiSaGaN** [comment]
@nox Yeah, I see that. You wanna close this one?
