### ISSUE TITLE
This project needs additional maintainers

### ISSUE THREAD

**Issue by nox** [crabtw/rust-bindgen#264]
I know @michaelwu is a maintainer, but he is very busy and no one ends up doing triaging around here. Given I'm the one asking, I'll be happy to take this burden off your backs.

**Comment by nox** [comment]
By new I meant additional, not planning a takeover obviously. :)

**Comment by Yamakaky** [comment]
I can help with the pull requests, at least.

**Comment by crabtw** [comment]
@nox, @Yamakaky I have added both of you as collaborators. Thanks :)

**Comment by crabtw** [comment]
BTW, if someone wants to help publish crate, I can add the ownership.

**Comment by nox** [comment]
@crabtw Thanks!

**Comment by nox** [comment]
I'll be happy to help with publishing.

**Comment by larsbergstrom** [comment]
@crabtw Thanks a ton - that will really help our efforts to get this working for the wide set of C++ libraries we're trying to work with from Servo.

**Comment by crabtw** [comment]
@nox I have added you as owner of bindgen and bindgen_plugin crates

**Comment by nox** [comment]
Cool, thanks a lot again.

Closing this, but if anyone wants some rights feel free to comment again.

**Comment by Yamakaky** [comment]
@crabtw Could you also add me? I would like to make a release nearly.

**Comment by crabtw** [comment]
@Yamakaky done :)
