### ISSUE TITLE
Enum_ and Struct_

### ISSUE THREAD

**Issue by Yamakaky** [crabtw/rust-bindgen#266]
Why do you generate for example `Struct_error` then `type error = Struct_error` ?

**Comment by Yamakaky** [comment]
I think it is to differentiate between `struct error` and `error` in c, when the definition and the typedef are not on the same instruction. If they are, though, I think you could directly output a rust `struct error`.

**Comment by nox** [comment]
We then need to track that renaming, in case some structure refers to `struct error` instead of `error`. I would like us to handle the case in #169 first.

**Comment by Yamakaky** [comment]
In fact, #169 is what I would like us to do ^^
