### ISSUE TITLE
Change in behavior between 0.15 and 0.16

### ISSUE THREAD

**Issue by iopq** [crabtw/rust-bindgen#269]
0.15 would generate `pub const CAFFE_TRAIN: ::libc:c_uint = 0` and the 0.16 version puts it inside of an enum so that `CAFFE_TRAIN` isn't actually found.

It now looks like this: `pub enum Enum_CaffePhase { CAFFE_TRAIN = 0, CAFFE_TEST = 1, }`

The repo in question:
https://github.com/ajtulloch/caffe.rs

I've forked it to:
https://github.com/iopq/caffe.rs and it doesn't compile with newer bindgen

Is this on purpose? Should I just use rewrite it using the newer version? Because all the dependencies for 0.15 no longer compile on the newest Nightly.

**Comment by nox** [comment]
A bump between `0.n` and `0.n+1` implies breaking changes, as per crates.io's rules. Neverless, [some](https://github.com/crabtw/rust-bindgen/pull/247#issuecomment-171578277) [people](https://github.com/crabtw/rust-bindgen/issues/255) pointed out that there are issues with enums in current Rust, so we [must implement a flag to disable generating enums as consts like previously](https://github.com/crabtw/rust-bindgen/pull/247#issuecomment-172069590).

Would you be interested in participating to that project by implementing such a flag? :)

**Comment by nox** [comment]
See #276 if you would rather not use Rust enums.
