### ISSUE TITLE
Use default Clone derivation

### ISSUE THREAD

**Issue by Yamakaky** [crabtw/rust-bindgen#271]
Currently, we add the following definition:
```rust
impl ::std::clone::Clone for Union_Unnamed1 {
    fn clone(&self) -> Self { *self }
}
```
Couldn't we simply use the default derived implementation?

**Comment by nox** [comment]
Sure, if they derived `Clone`… But unions are arrays, which is probably why they don't.

**Comment by nox** [comment]
@Yamakaky Did you cover this in your Clone patch?

**Comment by Yamakaky** [comment]
To answer you question: I detect if one of the members is a big array or contains a big array. It could be adapted for this case.
