### ISSUE TITLE
'Derive Debug' on unions and enums

### ISSUE THREAD

**Issue by dimbleby** [crabtw/rust-bindgen#282]
I have a [binding](https://github.com/dimbleby/rust-c-ares) to [c-ares](https://github.com/c-ares/c-ares).  Regenerating my [FFI](https://github.com/dimbleby/rust-c-ares/blob/master/c-ares-sys/src/ffi.rs) with the latest `bindgen` results in compile errors, for a couple of reasons:

The first is:

    src/ffi.rs:101:5: 101:31 error: the trait `core::fmt::Debug` is not implemented for the type `ffi::Union_Unnamed1` [E0277]

That is, `bindgen` is not deriving Debug for this type, so it's not allowed to derive Debug for types containing it.  This one I think is unambiguously a `bindgen` bug.

The second is slightly more complex:

    src/ffi.rs:131:5: 131:31 error: the trait `core::fmt::Debug` is not implemented for the type `libc::unix::in_addr` [E0277]

The [c-ares header file](https://github.com/c-ares/c-ares/blob/master/ares.h) makes use of `struct in_addr`, which `bindgen` translates to `Struct_in_addr`.  I make this compile, in a cross-platforrm way, by adding this line:

```rust
pub type Struct_in_addr = ::c_types::in_addr;
```

... where, on unix systems, `::c_types::in_addr` is just `libc::unix::in_addr` - which doesn't implement Debug.

It's not so clear to me what can be done about this one.

**Comment by Yamakaky** [comment]
Related to https://github.com/crabtw/rust-bindgen/pull/267.
On it.

**Comment by nox** [comment]
Are you making a new flag to disable Debug deriving?

**Comment by Yamakaky** [comment]
No

**Comment by nox** [comment]
So what's the plan? To ignore derivation for types using large unions and undefined types?

**Comment by Yamakaky** [comment]
Well, I think the simpler for now would be to not enable it by default, and then improve it. On it.

**Comment by nox** [comment]
Cool. :)

**Comment by Yamakaky** [comment]
Oops, auto-close.
By default, the derive(Debug) is disabled. Now, your problem!
1) could you add more context? What is in the cunion corresponding to Union_Unnamed1?
2) I don't think we can do something, except open a PR to implement Debug on this type.
Is there a mean to detect if a type implements Debug? It would be less error-prone than manually handling edge-cases.

**Comment by dimbleby** [comment]
My original report included links to both input and output files.  Looks like `Union_Unnamed1` is

```
struct ares_in6_addr {
  union {
    unsigned char _S6_u8[16];
  } _S6_un;
};
```

(but that was just the first example of several similar failures).

If you'd like to experiment with `bindgen`'s treatment of the c-ares header, suggest: clone my repository (c-ares is included as a submodule), then `cd c-ares-sys`, `./generate-ffi.sh`, `cargo build`.

**Comment by dimbleby** [comment]
PS forgot to say - thanks for the quick action on this!

**Comment by Yamakaky** [comment]
Ahah: I only check structs members, not unions ^^

**Comment by Yamakaky** [comment]
Should be good for 1). You can activate the debug generation with -derive-debug

**Comment by Yamakaky** [comment]
Seems solved.
