### ISSUE TITLE
Code generation options

### ISSUE THREAD

**Issue by Yamakaky** [crabtw/rust-bindgen#285]
Adding boolean flags to function doesn't scale. Maybe we should pass a config struct with the boolean flags inside?

**Comment by nox** [comment]
I'm not sure what you mean, isn't that what we do already? We pass around `BindgenOptions`.

**Comment by Yamakaky** [comment]
For example, with cenum_to_rs: you added rust_enums, I added derive_debug. I think we should pass BindgenOptions instead.

**Comment by nox** [comment]
Oh. I just pass an option if there is only one, and the struct if there are more.

**Comment by Yamakaky** [comment]
Let's do that.
