### ISSUE TITLE
Allow use without std

### ISSUE THREAD

**Issue by tbelaire** [crabtw/rust-bindgen#303]
Hi, I'm trying to compile a bunch of linux headers for a kernel module.
LLVM chokes on the entire kernel, so I'm just copy and pasting the functions I need into one header.

I am using `no_std`, and have a replacement `::raw::c_int` and such, and I'd like to have bindgen just emit `::raw::c_int` instead of `::std::os::raw::c_int`.

**Comment by Yamakaky** [comment]
You mean using only core?

**Comment by tbelaire** [comment]
Yes.

**Comment by Yamakaky** [comment]
I'm not sure it would be possible to just output `::raw::c_int`, I think it would not compile with other projects than yours.

**Comment by tbelaire** [comment]
What about if the root module was configurable?  Default would be `::std::os::raw`, but it could be overridden?

**Comment by tbelaire** [comment]
Really, this problem was solved on my end by defining a module `std` in my crate.  That's a bit silly though.

**Comment by Yamakaky** [comment]
Closing in favour of https://github.com/crabtw/rust-bindgen/issues/316
