### ISSUE TITLE
Guards that use `__INCLUDE_LEVEL__` don't work right

### ISSUE THREAD

**Issue by jmesmon** [crabtw/rust-bindgen#304]
systemd uses an include level guard in a private header to ensure it is never direcly included:

```c
/* _sd-common.h excerpt */
#if __INCLUDE_LEVEL__ <= 1
#error "Do not include _sd-common.h directly; it is a private header."
#endif
```
Trying to run bindgen on a header that includes `_sd-common.h` results in unexpected failures:

```sh
$ ./target/debug/bindgen -match sd-bus-vtable.h -I /usr/lib/clang/3.7.1/include/ /usr/include/systemd/sd-bus-vtable.h 
/usr/include/systemd/_sd-common.h:26:2: error: "Do not include _sd-common.h directly; it is a private header."
```
(`-I` flag included to work around #85)

**Comment by Yamakaky** [comment]
Well, it seems that it's the expected behavior, what do you want to change in bindgen?

**Comment by jmesmon** [comment]
The issue is that the include level reported by bindgen is off by one: normally, header files are included from a source file. It appears that bindgen is referencing header files directly (so the include level is 1 less that in would be if the header were included normally)

**Comment by Yamakaky** [comment]
I'm not sure it should be solved in bindgen. A fix would be to write a header which includes sd-common.

**Comment by jmesmon** [comment]
I guess my problem is that the normal way of using bindgen is to give it a header directly. Having to write a header that just is a wrapper around the header I care about for every bindgen invocation just to ensure they are parsed as expected shouldn't be required.

**Comment by Yamakaky** [comment]
@nox?

**Comment by nox** [comment]
There is not much we can do here IMO. Include level starts at 0, is incremented to 1 when including `_sd-common.h` and the whole thing errors out.

**Comment by nox** [comment]
You might be able to use this:

```
       -include <filename>
              Adds an implicit #include into the predefines buffer which is read before the source file is
              preprocessed.
```
