### ISSUE TITLE
Structs generated as enums

### ISSUE THREAD

**Issue by petehayes102** [crabtw/rust-bindgen#309]
For libs such as [CZMQ](https://github.com/zeromq/czmq), many struct definitions are provided in code only, rather than in the header. This means that bindgen produces enums instead of structs, which is problematic if one wanted to use struct members...

For example (from CZMQ):

**czmq_library.h**
```
typedef struct _zcertstore_t zcertstore_t;
```

**zcertstore.c**
```
struct _zcertstore_t {
    // members...
};
```

**rust-bindgen output**
```
pub enum Struct__zcertstore_t { }
pub type zcertstore_t = Struct__zcertstore_t;
```

I'm not saying that this is an error, but I'm wondering if someone knows of a way to resolve these missing struct member definitions? I suppose I could ship a separate header file with the missing definitions, but if there's a way for bindgen to handle this, that'd be grand!

**Comment by Yamakaky** [comment]
This is the expected behaviour, `_zcertstore_t` is an implementation detail. If you need to add the complete definition, it's a problem of the c api of the library, except if you are doing obscure hacking ^^.
I think the only way is to manually add the definitions.

**Comment by petehayes102** [comment]
Ok, I thought that was probably the case, but wanted to check on the off chance that bindgen had some magic for parsing C code as well as headers.

Thanks for the help mate.

**Comment by Yamakaky** [comment]
In fact it should, try to put both .c and .h inside bindgen.

**Comment by petehayes102** [comment]
Hey awesome! That worked. The only problem is that there are lots of C files to parse and it seems bindgen only accepts a single file. I was hoping that I could wildcard it but I get an error:
```
$ bindgen -l czmq ../czmq/src/z*.c

libclang: crash detected during parsing: {
  'source_filename' : ''
  'command_line_args' : ['-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/', '../czmq/src/zactor.c', '../czmq/src/zarmour.c', '../czmq/src/zauth.c', '../czmq/src/zauth_v2.c', '../czmq/src/zbeacon.c', '../czmq/src/zbeacon_v2.c', '../czmq/src/zcert.c', '../czmq/src/zcertstore.c', '../czmq/src/zchunk.c', '../czmq/src/zclock.c', '../czmq/src/zconfig.c', '../czmq/src/zctx.c', '../czmq/src/zdigest.c', '../czmq/src/zdir.c', '../czmq/src/zdir_patch.c', '../czmq/src/zfile.c', '../czmq/src/zframe.c', '../czmq/src/zgossip.c', '../czmq/src/zgossip_msg.c', '../czmq/src/zhash.c', '../czmq/src/zhashx.c', '../czmq/src/ziflist.c', '../czmq/src/zlist.c', '../czmq/src/zlistx.c', '../czmq/src/zloop.c', '../czmq/src/zmakecert.c', '../czmq/src/zmonitor.c', '../czmq/src/zmonitor_v2.c', '../czmq/src/zmsg.c', '../czmq/src/zmutex.c', '../czmq/src/zpoller.c', '../czmq/src/zproc.c', '../czmq/src/zproxy.c', '../czmq/src/zproxy_v2.c', '../czmq/src/zrex.c', '../czmq/src/zsock.c', '../czmq/src/zsocket.c', '../czmq/src/zsockopt.c', '../czmq/src/zstr.c', '../czmq/src/zsys.c', '../czmq/src/zthread.c', '../czmq/src/ztimerset.c', '../czmq/src/ztrie.c', '../czmq/src/zuuid.c'],
  'unsaved_files' : [],
  'options' : 0,
}
```

Any way to pass multiple sources?

**Comment by Yamakaky** [comment]
Not for now, it seams. You can create a `.h` which `#include` the files you need, though.
