### ISSUE TITLE
bindgen cannot find standard C headers

### ISSUE THREAD

**Issue by drbo** [crabtw/rust-bindgen#311]
On my system, bindgen cannot find some standard C headers because the library include path is not set properly (the first component is relative, not absolute).

**Comment by Yamakaky** [comment]
which system?

**Comment by drbo** [comment]
Fedora 24 Workstation.  Installed via cargo install.

**Comment by Yamakaky** [comment]
I never used Fedora. Do you have an idea of what could be the problem and a possible solution?

**Comment by drbo** [comment]
The problem is that bindgen doesn't look in the Clang-specific include directory.

**Comment by Yamakaky** [comment]
Solution: use `clang -x c -v -E /dev/null` to get the include path.

**Comment by Yamakaky** [comment]
Well now since `cargo run -- -v t.c` shows that it uses the same standard directories than clang... Is there a difference between this command and `clang -x c -v -E /dev/null`?

**Comment by Yamakaky** [comment]
Not directly related, but could you test https://github.com/crabtw/rust-bindgen/issues/314 on Fedora please?

**Comment by Yamakaky** [comment]
No @drbo ?

**Comment by drbo** [comment]
git HEAD does not work.  Still cannot find `stddef.h`.

**Comment by Yamakaky** [comment]
Could you run `clang -x c -v -E /dev/null` please? I don't have enough info to solve your problem.

**Comment by Yamakaky** [comment]
Oh: could you try to replace `p.push("lib");` by `p.push("lib");` in src/lib:get_include_dir?

**Comment by drbo** [comment]
Clang's include path is
```
/usr/local/include
/usr/bin/../lib64/clang/3.8.0/include
/usr/include
```

**Comment by Yamakaky** [comment]
Yes, that's it. The fix should work.

**Comment by Yamakaky** [comment]
Closing for https://github.com/crabtw/rust-bindgen/issues/317
