### ISSUE TITLE
'error: type name `size_t` is undefined or not in scope'

### ISSUE THREAD

**Issue by pwoolcoc** [crabtw/rust-bindgen#313]
When generating bindings from a header file that uses `size_t`, `bindgen` is using `size_t` as a type in the resulting rust code, but there is no type with that name. in `src/clangll.rs` of this project, I see this line near the top: `pub type size_t = ::std::os::raw::c_ulong`.  Putting that line in my rust code makes it compile fine. I have a simple example to reproduce:

```bash
$ cat test.h
/* test.h */
#include "stddef.h"

size_t func(void);
$ 
$ bindgen -match test -o test.rs test.h
$ rustc test.rs
test.rs:4:22: 4:28 error: type name `size_t` is undefined or not in scope [E0412]
test.rs:4     pub fn func() -> size_t;
                               ^~~~~~
test.rs:4:22: 4:28 help: run `rustc --explain E0412` to see a detailed explanation
test.rs:4:22: 4:28 help: no candidates by the name of `size_t` found in your project; maybe you misspelled the name or forgot to import an external crate?
```

**Comment by emilio** [comment]
If you add `-match test`, the `stddef.h` file isn't matched, and thus bindings for its types are not generated.

The ideal way IMHO would be translating stddef types automatically to rust types (i.e `size_t` -> `usize`, `uint8_t` -> `u8`, ...).

**Comment by pwoolcoc** [comment]
I understand, just seems like a waste to pull in the entire `stddef.h` just to get `size_t`.

**Comment by Yamakaky** [comment]
It should be `#include <stddef.h>`, shouldn't it? Strange bindgen doesn't print a warning like "....h not found"
@emilio WIP (https://github.com/crabtw/rust-bindgen/pull/256)

**Comment by Yamakaky** [comment]
WIP https://github.com/crabtw/rust-bindgen/pull/256
