### ISSUE TITLE
Deriving `Clone` does not work for structs with large array members

### ISSUE THREAD

**Issue by bsteinb** [crabtw/rust-bindgen#319]
04421afdbedc5aa5f925f42241ef04cf9e41dfe8 replaces explicit implementations of `Clone` by a derive clause. This does not work for structs which contain large arrays. In my case I get
```rust
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Struct__opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut Struct___darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
```
and the compiler complains that
```
error: the trait `core::clone::Clone` is not implemented for the type `[i8; 8176]` [E0277]
```

**Comment by Yamakaky** [comment]
Should be good, could you check?

**Comment by bsteinb** [comment]
No, it is not. The clone-via-deref trick requires `Copy` types, but no deriving clause for `Copy` is emitted for types with an explicit `Clone` `impl` now. Before 04421af, these types had a deriving clause for `Copy` and an explicit `impl` for `Clone`.

**Comment by Yamakaky** [comment]
Oh, I see.

**Comment by bsteinb** [comment]
5e1b69c5071ff698550fc1f91ed1b4edb52b8adc seems to have resolved the issue.

**Comment by Yamakaky** [comment]
Cool!
