### ISSUE TITLE
Unwanted Derive Debug is back

### ISSUE THREAD

**Issue by dimbleby** [crabtw/rust-bindgen#342]
As in #282, I have a binding to a C interface which uses an `in_addr`; and `libc::in_addr` does not derive Debug.

As a result, after autogenerating, I get this:

````
   Compiling c-ares-sys v0.11.0 (file:///data/build/rust-c-ares/c-ares-sys)
src/ffi.rs:122:5: 122:24 error: the trait bound `libc::in_addr: std::fmt::Debug` is not satisfied [E0277]
src/ffi.rs:122     pub ipaddr: in_addr,
                   ^~~~~~~~~~~~~~~~~~~
src/ffi.rs:120:10: 120:15 note: in this expansion of #[derive_Debug] (defined in src/ffi.rs)
src/ffi.rs:122:5: 122:24 help: run `rustc --explain E0277` to see a detailed explanation
src/ffi.rs:122:5: 122:24 note: `libc::in_addr` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
src/ffi.rs:122:5: 122:24 note: required for the cast to the object type `std::fmt::Debug`
error: aborting due to previous error
error: Could not compile `c-ares-sys`.

To learn more, run the command again with --verbose.
````

Please either:
- turn off debug-deriving by default
- provide a command line option allowing me to disable it
- (or something else that'll let this work!)

Thanks!

**Comment by Yamakaky** [comment]
Oops, sorry ^^
BTW, if someone find a way to reliably detect if a type implements Debug, I want it.

**Comment by dimbleby** [comment]
Thanks!

**Comment by Yamakaky** [comment]
I know it's not perfect, but did you consider manually removing the derives?

**Comment by dimbleby** [comment]
Yes, sure.  

- my process for generating the FFI already involves [applying a small patch](https://github.com/dimbleby/rust-c-ares/blob/f27d6697a7ea5d2d8219961147bbe02ddefd8604/c-ares-sys/generate-ffi.sh#L12)
- and indeed in the brief period between my reporting this and your fixing it, manually removing the problematic derive is [exactly what I did](https://github.com/dimbleby/rust-c-ares/blob/54d196732acd5c9d2bc2dc61c3376761c334c868/c-ares-sys/ffi.patch#L28).

**Comment by Yamakaky** [comment]
Ok. Don't hesitate to report things you think could be automated.
