### ISSUE TITLE
Can we use clang-cl as backend compiler?

### ISSUE THREAD

**Issue by javagg** [crabtw/rust-bindgen#345]
I have some msvc-sepcific headers which need to be processed with clang in msvc-compatible mode, Is there a way to do that?

**Comment by Yamakaky** [comment]
Good question. It seems that there are some flags which helps for that http://clang.llvm.org/docs/MSVCCompatibility.html. Maybe `cargo run -- header.h -- -fms-compatibility -fms-extensions` will do the job.
BTW, can you confirm that `bindgen` works fine on windows? Do you have to set env variables or some other trick or is it OOTB?

**Comment by javagg** [comment]
I've tried some simple header files, bindgen works just fine. no env variables need to be set on my system.

**Comment by Yamakaky** [comment]
Cool. And for your problem?

**Comment by javagg** [comment]
No, it didn't work. The output is empty.

**Comment by Yamakaky** [comment]
try `--driver-mode=cl`

**Comment by javagg** [comment]
It worked with the updated code! thanks!
