### ISSUE TITLE
rustc can't compile generated code

### ISSUE THREAD

**Issue by ujh** [crabtw/rust-bindgen#359]
I'm currently trying to get [caffe.rs](https://github.com/ujh/caffe.rs) to compile again. I've updated to the latest version of bindgen and changed [build.rs](https://github.com/ujh/caffe.rs/blob/master/build.rs) and it  indeed produces a ffi.rs file. Unfortunately when rustc tries to compile it I get the following error:

```
uh@macaron:~/Personal/caffe.rs (master)$ cargo build
   Compiling caffe v0.1.0 (file:///Users/uh/Personal/caffe.rs)
/Users/uh/Personal/caffe.rs/target/debug/build/caffe-fb538219bafeb767/out/lib/ffi.rs:3:3: 3:4 error: an inner attribute is not permitted in this context
/Users/uh/Personal/caffe.rs/target/debug/build/caffe-fb538219bafeb767/out/lib/ffi.rs:3 #![allow(dead_code,
                                                                                         ^
/Users/uh/Personal/caffe.rs/target/debug/build/caffe-fb538219bafeb767/out/lib/ffi.rs:3:3: 3:4 help: place inner attribute at the top of the module or block
error: aborting due to previous error
error: Could not compile `caffe`.

To learn more, run the command again with --verbose.
```

This seems to be a parsing issue with the latest nightly compiler. I don't fully understand if it's something that I can fix myself or if it is a bindgen issue. For completeness here's the generated file:

``` rust
/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum CaffePhase { CAFFE_TRAIN = 0, CAFFE_TEST = 1, }
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum CaffeMode { CAFFE_CPU = 0, CAFFE_GPU = 1, }
pub enum CaffeNet { }
pub enum CaffeBlob { }
pub enum CaffeSolver { }
#[link(name = "caffe", kind = "dylib")]
extern "C" {
    pub fn CaffeNetInit(param_file: *const ::std::os::raw::c_char,
                        phase: CaffePhase) -> *mut CaffeNet;
    pub fn CaffeNetCopyTrainedLayersFrom(net: *mut CaffeNet,
                                         trained_file:
                                             *const ::std::os::raw::c_char);
    pub fn CaffeNetForwardPrefilled(net: *mut CaffeNet);
    pub fn CaffeNetGetBlobByName(net: *mut CaffeNet,
                                 name: *const ::std::os::raw::c_char)
     -> *mut CaffeBlob;
    pub fn CaffeNetBackward(net: *mut CaffeNet);
    pub fn CaffeNetFree(net: *mut CaffeNet);
    pub fn CaffeBlobCPUData(blob: *const CaffeBlob)
     -> *const ::std::os::raw::c_float;
    pub fn CaffeBlobMutableCPUData(blob: *mut CaffeBlob)
     -> *mut ::std::os::raw::c_float;
    pub fn CaffeBlobCount(blob: *const CaffeBlob)
     -> ::std::os::raw::c_ulonglong;
    pub fn CaffeBlobSetCPUData(blob: *mut CaffeBlob,
                               data: *mut ::std::os::raw::c_float);
    pub fn CaffeBlobFree(blob: *mut CaffeBlob);
    pub fn CaffeSolverInit(param_file: *const ::std::os::raw::c_char)
     -> *mut CaffeSolver;
    pub fn CaffeSolverNet(solver: *mut CaffeSolver) -> *mut CaffeNet;
    pub fn CaffeSolverSolve(solver: *mut CaffeSolver);
    pub fn CaffeSolverFree(solver: *mut CaffeSolver);
    pub fn CaffeSetMode(mode: CaffeMode);
}
```

**Comment by Yamakaky** [comment]
Which rust version do you use?

**Comment by ujh** [comment]
The latest nightly:

```
rustcuh@macaron:~$ rustc --version
rustc 1.11.0-nightly (bb4a79b08 2016-06-15)
```

But it also happened a few days ago.

**Comment by ujh** [comment]
If I manually remove the `#![allow(...)]` then it works.

**Comment by Yamakaky** [comment]
I don't have the same problem on nightly...

**Comment by ujh** [comment]
That is actually great. Now I know that I can fix it. 👍  Do you have an example on how you use it? As I said I'm currently trying to get a code base to compile again that I didn't write. The generated rust code is included like this: https://github.com/ujh/caffe.rs/blob/master/src/ffi.rs. And the code the generate is is written like this: https://github.com/ujh/caffe.rs/blob/master/build.rs. I'm thinking that maybe I'm just including it in the wrong way?

**Comment by Yamakaky** [comment]
Why don't you just generate ffi.rs using bindgen then use it from an other module?

**Comment by Twinklebear** [comment]
The problem comes from `include!` not accepting the inner attribute I think, but I'm unsure quite why (not familiar with how `include!` works.) The issue comes up especially for projects that generate bindings on the fly, like [ispc-rs](https://github.com/Twinklebear/ispc-rs) where we compile some code to a native lib and header and feed that header to bindgen to generate bindings. I'm not sure if there's a better way to just use the module in the build directory, for native code generate Cargo recommends: `include!(concat!(env!("OUT_DIR"), "/hello.rs"));` which will result in the error.

**Comment by ujh** [comment]
Thank you so much! I ended up just pasting in the generated Rust code into the crate. It won't change that much anyway. 👍

**Comment by nlfiedler** [comment]
I am seeing this issue with rustc 1.10.0 on Mac. I'm generating the bindings on the fly using `build.rs` so manually editing the file is not feasible (each system varies slightly, hence it is generated each time). Is there a solution to this, other than stopping everything and editing a file by hand?

**Comment by Twinklebear** [comment]
@nlfiedler the issue is actually with `include!` not handling top-level inner attributes: https://github.com/rust-lang/rfcs/issues/752 the work around I've gone with is to write the generated bindings to a string and wrap the bindings in a module when creating the file: https://github.com/Twinklebear/ispc-rs/blob/master/src/lib.rs#L401-L411

**Comment by nlfiedler** [comment]
@Twinklebear Excellent, thanks for the explanation and the work-around.

**Comment by Yamakaky** [comment]
Could you please make a PR to update the README?

**Comment by Twinklebear** [comment]
Done, #383
