### ISSUE TITLE
Multiple match options broken?

### ISSUE THREAD

**Issue by ArtemGr** [crabtw/rust-bindgen#362]
With the latest bindgen (abb7202) I can't use it with multiple match options. It worked fine before.

For a contrived example,
`bindgen --match=filter.h /usr/include/lzma.h`
works.

`bindgen --match=index.h /usr/include/lzma.h`
works.

`bindgen --match=filter.h --match=index.h /usr/include/lzma.h`
says "Invalid arguments."

**Comment by Yamakaky** [comment]
Oh yeah, it's a mistake in the docopt string. See main.rs

**Comment by ArtemGr** [comment]
Something like this?
http://try.docopt.org/?doc=Usage%3A%0D%0A++bindgen+[options]%0D%0A++bindgen+[options]+(--match%3D%3Cname%3E+...)%0D%0A%0D%0AOptions%3A%0D%0A++--match%3D%3Cname%3E++++++Whatever.%0D%0A++--foo%0D%0A++--bar%0D%0A%0D%0A%0D%0A&argv=--match%3D123+--match%3D234+--foo+--bar

( cf. http://stackoverflow.com/questions/18468123/option-multiplicity-with-docopt )

**Comment by Yamakaky** [comment]
Yes, plus a modification in args_to_opts. Do you want to try? It's a simple fix.

**Comment by ArtemGr** [comment]
Yeah, I'll give it a shot later. Can't promise that it'll be soon.

**Comment by ArtemGr** [comment]
Submitted a pull request, check it out.   : )
