### ISSUE TITLE
ERROR:bindgen: unsupported type `WChar` on Window

### ISSUE THREAD

**Issue by javagg** [crabtw/rust-bindgen#373]
c.cpp
```
typedef const wchar_t *LPCWSTR;
```

When I run 
```
bindgen c.cpp
```
The output is:
```
ERROR:bindgen: unsupported type `WChar` (c.cpp:1:24)
```

my clang is:
```
> clang -v
clang version 3.8.0 (branches/release_38)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```
my rust version is:
```
> rustc -V
rustc 1.9.0 (e4e8b6668 2016-05-18)
> cargo --version
cargo 0.10.0-nightly (10ddd7d 2016-04-08)

```

**Comment by Yamakaky** [comment]
As wchar_t's size is implementation defined, it can change between compilers...

**Comment by javagg** [comment]
@Yamakaky But clang on windows can parse this witout any error

**Comment by Yamakaky** [comment]
Yes, I know, but what rust type would you use to represent it?

**Comment by javagg** [comment]
on windows, sizeof(wchar_t) == 2 and we can use 'unsigned short'  to represent it.

**Comment by Yamakaky** [comment]
http://www.firstobject.com/wchar_t-string-on-linux-osx-windows.htm
> Unlike Windows UTF-16 2-byte wide chars, wchar_t on Linux and OS X is 4 bytes UTF-32 (gcc/g++ and XCode). On cygwin it is 2 (cygwin uses Windows APIs).

**Comment by Yamakaky** [comment]
Ahah, so stupid: https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/type.wchar_t.html

**Comment by Yamakaky** [comment]
Doest it fixes you problem?

**Comment by javagg** [comment]
I will have a try later! And many thanks!!!
