### ISSUE TITLE
Seems to generate invalid 'va_list' types on OSX

### ISSUE THREAD

**Issue by shadowmint** [crabtw/rust-bindgen#68]
For example, running on the python headers for:

    PyAPI_FUNC(PyObject *) PyUnicode_FromFormatV(const char*, va_list);

Generates:

    pub fn PyUnicodeUCS2_FromFormatV(arg1: *c_schar, arg2: va_list) ->  *mut PyObject;

Using -builtin generates the __builtin_va_list symbol in the header, but the actual symbol definitions are not correct.

Work around, in vim: :.,$s/ va_list/ __builtin_va_list/g

**Comment by Yamakaky** [comment]
I tested on my computer, I had no problem.
