### ISSUE TITLE
Procedural macro

### ISSUE THREAD

**Issue by SiegeLord** [crabtw/rust-bindgen#77]
What do you think of turning bindgen into a procedural macro to skip the intermediate FFI file?

A possible api would be:
~~~rust
bind_c!("some_file.h")
bind_c!(raw = "
    #define BAD_LIBRARY_NEEDS_THIS
    #include \"some_bad_library.h\"
")
bind_c!("some_file.h", match="foo") // and so on for the usual bindgen command line arguments
~~~

I'm willing it give it a try myself, but you're more familiar with the code so this may seem more crazy to you.

**Comment by Yamakaky** [comment]
`bindgen!` exists.
