### ISSUE TITLE
LLVM assertion during binding generation

### ISSUE THREAD

**Issue by TomBebbington** [crabtw/rust-bindgen#89]
I get the following output with Rust master:

```
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-linux/build/src/llvm/include/llvm/Support/CommandLine.h:682: void llvm::cl::parser<DataType>::addLiteralOption(const char*, const DT&, const char*) [with DT = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*); DataType = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*)]: Assertion `findOption(Name) == Values.size() && "Option already exists!"' failed.
```
when I try to generate bindings for LibJIT using `./bindgen ../libjit/include/jit/jit.h` after building it.

**Comment by fitzgen** [comment]
Can anyone confirm that I am also hitting this issue?

    $ ./target/bindgen --help
    dyld: Library not loaded: @rpath/libclang.dylib
      Referenced from: /Users/fitzgen/src/rust-bindgen/./target/bindgen
      Reason: image not found
    Trace/BPT trap: 5

**Comment by jan-hudec** [comment]
Of course that will break at the moment rust starts being itself linked dynamically, which it will at the moment it is packaged, because Debian policy forbids static linking of anything that can be linked dynamically.

**Comment by henrix** [comment]
Hi, this isn't related to rust, but I have a similar error when executing a demp application which uses my self created shared lib. My shared lib is linked against OpenCL which I need. The test app is based on QT and QT printsupport (realtime plots with QCustomPlot) which seem to also require a QT integrated OpenCL. Here is my error output:

`test-libaudio-x15: /build/ti-llvm-3.3-DgVvHD/ti-llvm-3.3-3.3-git20150413/include/llvm/Support/CommandLine.h:674: void llvm::cl::parser<DataType>::addLiteralOption(const char*, const DT&, const char*) [with DT = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*); DataType = llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*)]: Assertion »findOption(Name) == Values.size() && "Option already exists!"« failed.`

Would be great if someone could give me some suggestions how to solve this problem.

Thanks!

**Comment by Yamakaky** [comment]
No idea, sorry... If you find the solution, I'm interested, it may help me to fix the bindgen plugin.
