### ISSUE TITLE
Making output nicer

### ISSUE THREAD

**Issue by errordeveloper** [crabtw/rust-bindgen#93]
I'm quite sure that it should be rather easy to apply some basic transforms and thereby make binding code a little friendlier.

Two things I can think of are:

  - given a namespace prefix `libfoo_`, produce `mod libfoo` removing the prefix from function names
  - change naming style, e.g. lower-case all function names

**Comment by Yamakaky** [comment]
I prefer not to change the sumbols names too much, it's more difficult to search in the doc.
